config/routes.rb
Rails.application.routes.draw do

  get 'politika', :to => redirect('/Politika.pdf')
  get 'calendar_2018', :to => redirect('/calendar_2018.pdf')
  get 'calendar_2019', :to => redirect('/calendar_2019.pdf')

  resources :feedback do
    collection do
      post 'create'
      get :autocomplete_organization_name

    end
  end
  get 'sitemap' => 'main#sitemap'

  mount RedactorRails::Engine => '/redactor_rails'

  root 'main#index'
  get 'about' => "main#about"
  resources :main do
    collection do
      post 'global_search'
      post 'articles'
    end
  end

  resources :rmi
  resources :calendar, only: :index do
        member do
          get 'download_document'
        end
  end

  resources :classroom do
    collection do
      get 'show_video_list'
    end
  end

  resources :organization, :only =>  [:index]  do
    collection do
      get 'info'
      post 'info'
      get 'summary_nok'
      get 'equipment'
    end
  end

  resources :articles, :only =>  [:index, :show]  
  get 'rss' => 'articles#feed', format: 'rss'

  resources :subscribes
  get 'confirm_email' => 'subscribes#confirm'
  get 'unsubscribe' => 'subscribes#unsubscribe'
  post 'send_unsubscribe' => 'subscribes#send_unsubscribe'

    

  resources :statistics, :only =>  [:index]  do
    collection do
      get 'chart'
      get 'docs'
      get 'additionally'
    end

  end

  resources :ratings, only: [:index, :edit] do
    collection do
      get 'add_ambul'
      get 'add_hospital'
      get 'list'
      get 'add_question'
      get 'add_form'
      get 'thank_you'
      get 'edit_form'
      get 'edit_question'
      get 'edit_answer'
      post 'add_ambul'
      post 'add_hospital'
      post 'list'
      post 'add_question'
      post 'add_form'
      put 'edit_form'
      put 'edit_question'
      put 'edit_answer'
    end
  end

  resources :documents

  resources :about do
    collection do
      get 'tasks'
      get 'contacts'
      get 'departments'
      get 'phones'
      get 'vacancies'

    end
  end

  devise_for :users

  resources :eco, only: :index do
    collection do
      post 'create_eco_vote'

    end
  end

  resources :users do
    collection do
      get :autocomplete_organization_name
    end
  end

  namespace :admin do
    namespace :calendar do
      resources :calendar_list do
        member do
          get 'file_list'
          get 'download_document'
          delete 'remove_file'
        end
        collection do
          post 'upload_document'

        end
      end
      resources :calendar_report_type
      resources :calendar_schedule do
        collection do 
          get 'delete_list'
          post 'delete_list'
        end
        
      end
      
    end

    resources :main, only: :index
    resources :articles

    resources :documents do
      collection do
        post 'mass_deleting'
      end
    end
    
    resources :document_stages 

    resources :classroom, :only => [:index, :new, :show_video_list, :destroy, :show, :edit] do
      collection do
        post 'update_video_list'
        get 'update_video_list'
        get 'show_video_list'
        post 'create_video_file'

      end
      member do
        post 'edit'
      end

    end

    resources :organization

    resources :type_organization

    resources :rmi do
      collection do
        get 'theme'
        get 'answer'
        post 'create_answer'
      end

      member do

        get 'edit_theme'
        post 'edit_theme'
        delete 'destroy_theme'
        get 'edit_answer'
        post 'update_answer'

        delete 'destroy_answer'

      end

    end
    resources :vacancies do
      collection do
        post 'create_vacancy'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end

    resources :employees do
      collection do
        get 'get_employees'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end
    resources :department

    resources :users do
      collection do
        get :autocomplete_organization_name
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
        post 'reset_password'
      end
    end

    devise_for :users
  end

end

app/models/article.rb
# coding: utf-8
class Article < ActiveRecord::Base
	# 0 -новость
	# 1 - ?
	# 2 - видео
	# attr_accessible :title, :preview, :body, :published_at, :published_to, :user_id, :types, :vid_url, :image
	# has_attached_file :image, :styles => { :hd => "1080x720>", :xlarge => "1920x700>", :news =>"973x615#", :large => "750x300>", :medium => "300x300>",  :small => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/rails.png"
	# validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	scope :types_0, -> { where(types: 0)}
	scope :types_1, -> { where(types: 1)}
	scope :types_2, -> { where(types: 2)}
	scope :types_3, -> { where(types: 3)}
	scope :types_4, -> { where(types: 4)}
	scope :types_5, -> { where(types: 5)}
	scope :publics_to, -> { where("published_to > ?",Date.today)}
	# scope :publics, -> {where('published_at between ? and ?  and published_to > ? ', Date.parse('2014-01-01'), Date.today.end_of_day, Date.today.end_of_day)}
	scope :publics, -> {where('published_at between ? and ?  and published_to > ? ', Date.parse('2014-01-01'), Date.today.end_of_day, Date.today.end_of_day).order(created_at: :desc)}
	scope :published, -> {where(show: true).order(created_at: :desc)}
	scope :publics_at,  -> { where("published_at between ? and ?",Date.today.beginning_of_day, Date.today.end_of_day)}
	scope :last_day, -> {where(created_at: Time.now-21.hours..Time.now+3.hours)}
	belongs_to :user
	has_many :foto
	belongs_to :tag
	belongs_to :article_image

	def start_time
		self.created_at
	end

	TAGS = {123 => {name: "Тег (Выберите...)"}, 0 => {name: "Здравоохранение", color: "rgba-default"}, 1 => {name: "Информатизация", color: "rgba-blue"}, 2 => {name: "Статистика", color: "rgba-yellow"}, 3 => {name: "Деятельность МИАЦ'a", color: "rgba-purple"}}

	def self.add_article params,current_user
		Article.create(title:params[:title], types:params[:types], preview:params[:preview], body: params[:body], vid_url: (params[:vid_url] if params[:vid_url].present?), published_at: Time.now, published_to: Time.now, user_id: current_user.id)
	end

	def self.edit_article params
		Article.find(params[:id]) if Article.find(params[:id]).present?

	end
	def self.remove_article params
		Article.find(params[:id]).delete if Article.find(params[:id]).present?
	end

	def self.update_article params
		if Article.find(params[:id]).present?
			Article.find(params[:id]).update_attributes(title: params[:title],preview:params[:preview],body: params[:body])
		end
	end

	def self.search params
		Article.published.where('lower(body) like lower (?) OR lower(title) like lower (?)', "%#{params[:search]}%", "%#{params[:search]}%").order("created_at DESC")
	end

	def self.search_gl params
		Article.where('lower(body) LIKE lower (?) OR lower(title) LIKE lower (?)', "%#{params[:search]}%", "%#{params[:search]}%").order("created_at DESC")
	end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  
  # before_filter :check_user 
  # def check_user    
  #   redirect_to admin_main_index_path, alert: 'Доступ ограничен' if cannot? :manage, Article
  # end

  load_and_authorize_resource class: Article


  def index
    @articles = Article.order(created_at: :desc).paginate(per_page:5, page:params[:page])
  end

  def new
    @article = Article.new
  end

  def create
    if params[:tag_id].present?
      params[:article][:article_image_id]=Article.get_image_id params[:tag_id] 
      @article = Article.create(article_params)
      notice='Новость создана'
    else
      notice='Новость не создана. Заполните все поля. Поле тема обязательна к заполнению'
    end
    redirect_to :back, notice: notice
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to :back, notice: 'Новость удалена'
  end

  def update
    article = Article.find(params[:id])
    params[:article][:article_image_id]=Article.get_image_id params[:tag_id] if params[:tag_id].present?
    respond_to do |format|
      if article.update_attributes(article_params)
        format.html { redirect_to :back, notice: 'Новость обновлена' }
        format.json { respond_with_bip(article) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(article) }
      end
    end
  end



  private
    def article_params
      params.require(:article).permit!
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout :resolve_layout
  def index
    if params[:search].present?
      @articles = Article.paginate(page: params[:page], per_page: 6).search(params)
    else
      @articles = Article.published.paginate(page: params[:page], per_page: 6)
    end
  end

  def show
    @article = Article.find(params[:id])
    @title = @article.title
    if @article.present?
      @article.update_attributes(count_views: @article.count_views+1)    
    end
    redirect_to root_path unless @article.show


  end

  def feed    
    @articles = Article.published.order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end

  
  private
    def resolve_layout
      case action_name
      when "feed"
        false
      else
        "application"
      end
    end


  



end

app/views/articles/index.haml
- title 'Новости МИАЦ Калужской области'
- meta_tag :description, 'Последние новости по медицинской статистике Калуга'
- meta_tag :keywords, 'новости, МИАЦ Калуга'

.row
  -#.col-md-1
  .col-md-12

    .panel.panel-info{style:"font-size: 14px;"}
      .panel-heading
        %i
          .path
            Новости
            .pull-right{style: 'padding-left: 15px;'}
              =link_to rss_path, target: :blank, :rel => "alternate", :title => "RSS поток", :type => "application/rss+xml" do
                %i.fa.fa-rss
                RSS
            
            .pull-right
          
              =link_to new_subscribe_path, title: 'Оформить подписку на новости' do
                %i.fa.fa-envelope-o
                Подписаться



      .panel-body

        .pull-right
          .form-inline
            = form_tag(request.path, method: "get", class: "form-horizontal") do
              = text_field_tag :search, params[:search], placeholder: "Поиск по новостям", class: "form-control"
              = submit_tag 'Найти', class: 'btn btn-sm btn-primary'

        - unless @articles.present?
          .row
            .col-md-12
              %center
                %h2
                  Возможно вы ничего не нашли.
        - else
          -#.col-md-12
          -#  .pull-right
          -#    %form.form-inline
          -#      .form-group
                  -#= form_tag(request.path, method: "get", class: "form-horizontal") do

                  -#= text_field_tag :search, params[:search], placeholder: "Поиск по новостям", class: "form-control"
          %table.table.table-hover.table-condensed
          - @articles.each do |article|
            .my_panel
              .my_panel-heading
                .row
                  .col-md-6{style:'font-size: 13px;'}
                    .pull-left
                      %i.fa.fa-calendar
                      = I18n.l article.created_at, format: :long
                      ,
                      %i.fa-fw.fa.fa-eye{title: 'Просмотров', style:'cursor: pointer'}
                      =article.count_views



                  .col-md-6
                    .pull-right
                      =render 'shared/social_share'

              .panel-body
                
                .row-fluid
                  .col-md-12
                    -if article.body.present? && article.article_image.present?
                      
                      =image_tag("#{article.article_image.name}", style: "float: left; padding: 1em; width: 15%; ")                        
                      %h3.text-center=article.title
                      %br
                      %p= truncate( raw( sanitize(article.body.html_safe, :tags => %w(), :attributes => %w(id class style) ) ), :length => 130, :omission => "...")
                    -elsif article.body.present? && article.article_image.blank?
                      =image_tag("miac.png", style: "float: left; padding: 1em; width: 15%;")
                      %h3.text-center=article.title
                      %br
                      
                      = truncate( raw( sanitize(article.body.html_safe, :tags => %w(), :attributes => %w(id class style) ) ), :length => 130, :omission => "...")
                    -else
                      Описание новости не указано                    
                      

                .row
                  .col-md-12
                    .pull-right
                      %h4=link_to 'Подробнее', article_path(article), class: 'btn btn-sm btn-primary'
            %br
          %center
            = will_paginate @articles, :previous_label => t("<"), :next_label => t(">")

app/views/articles/show.haml
-if @article.show
  - meta_tag :keywords, @article.title
  .container-fluid
    .row
      .col-md-1
      .col-md-10
        .panel.panel-info
          .panel-heading
            .row
              .col-md-6
                .pull-left
                  %i.fa.fa-calendar
                  = I18n.l @article.created_at, format: :long
                  ,
                  %i.fa-fw.fa.fa-eye{title: 'Просмотров', style:'cursor: pointer'}
                  =@article.count_views


              .col-md-6
                .pull-right=render 'shared/social_share'

                .pull-right{style: 'padding-right:10px;'}
                  =link_to new_subscribe_path do
                    %i.fa.fa-envelope-o
                    Подписаться
                

          .panel-body
            

            .row
              .col-md-12
                -if @article.body.present? && @article.article_image.present?
                  
                  
                  =image_tag("#{@article.article_image.name}", style: "float: left; padding: 1em; width: 20%; ")
                  %h3.text-center= @article.title
                  = @article.body.html_safe 
                -elsif @article.body.present? && @article.article_image.blank?
                  
                 
                  =image_tag("miac.png", style: "float: left; padding: 1em; width: 20%;")
                  %h3.text-center= @article.title
                  = @article.body.html_safe
                -else
                  Описание новости не указано
                


              .row
                .col-md-12
                  .pull-right
                    
                    = link_to articles_path, class: "btn btn-sm btn-primary" do
                      %i.fa.fa-arrow-left       
                      К списку новостей