config/routes.rb
Rails.application.routes.draw do

  get 'politika', :to => redirect('/Politika.pdf')
  get 'calendar_2018', :to => redirect('/calendar_2018.pdf')
  get 'calendar_2019', :to => redirect('/calendar_2019.pdf')

  resources :feedback do
    collection do
      post 'create'
      get :autocomplete_organization_name

    end
  end
  get 'sitemap' => 'main#sitemap'

  mount RedactorRails::Engine => '/redactor_rails'

  root 'main#index'
  get 'about' => "main#about"
  resources :main do
    collection do
      post 'global_search'
      post 'articles'
    end
  end

  resources :rmi
  resources :calendar, only: :index do
        member do
          get 'download_document'
        end
  end

  resources :classroom do
    collection do
      get 'show_video_list'
    end
  end

  resources :organization, :only =>  [:index]  do
    collection do
      get 'info'
      post 'info'
      get 'summary_nok'
      get 'equipment'
    end
  end

  resources :articles, :only =>  [:index, :show]  
  get 'rss' => 'articles#feed', format: 'rss'

  resources :subscribes
  get 'confirm_email' => 'subscribes#confirm'
  get 'unsubscribe' => 'subscribes#unsubscribe'
  post 'send_unsubscribe' => 'subscribes#send_unsubscribe'

    

  resources :statistics, :only =>  [:index]  do
    collection do
      get 'chart'
      get 'docs'
      get 'additionally'
    end

  end

  resources :ratings, only: [:index, :edit] do
    collection do
      get 'add_ambul'
      get 'add_hospital'
      get 'list'
      get 'add_question'
      get 'add_form'
      get 'thank_you'
      get 'edit_form'
      get 'edit_question'
      get 'edit_answer'
      post 'add_ambul'
      post 'add_hospital'
      post 'list'
      post 'add_question'
      post 'add_form'
      put 'edit_form'
      put 'edit_question'
      put 'edit_answer'
    end
  end

  resources :documents

  resources :about do
    collection do
      get 'tasks'
      get 'contacts'
      get 'departments'
      get 'phones'
      get 'vacancies'

    end
  end

  devise_for :users

  resources :eco, only: :index do
    collection do
      post 'create_eco_vote'

    end
  end

  resources :users do
    collection do
      get :autocomplete_organization_name
    end
  end

  namespace :admin do
    namespace :calendar do
      resources :calendar_list do
        member do
          get 'file_list'
          get 'download_document'
          delete 'remove_file'
        end
        collection do
          post 'upload_document'

        end
      end
      resources :calendar_report_type
      resources :calendar_schedule do
        collection do 
          get 'delete_list'
          post 'delete_list'
        end
        
      end
      
    end

    resources :main, only: :index
    resources :articles

    resources :documents do
      collection do
        post 'mass_deleting'
      end
    end
    
    resources :document_stages 

    resources :classroom, :only => [:index, :new, :show_video_list, :destroy, :show, :edit] do
      collection do
        post 'update_video_list'
        get 'update_video_list'
        get 'show_video_list'
        post 'create_video_file'

      end
      member do
        post 'edit'
      end

    end

    resources :organization

    resources :type_organization

    resources :rmi do
      collection do
        get 'theme'
        get 'answer'
        post 'create_answer'
      end

      member do

        get 'edit_theme'
        post 'edit_theme'
        delete 'destroy_theme'
        get 'edit_answer'
        post 'update_answer'

        delete 'destroy_answer'

      end

    end
    resources :vacancies do
      collection do
        post 'create_vacancy'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end

    resources :employees do
      collection do
        get 'get_employees'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end
    resources :department

    resources :users do
      collection do
        get :autocomplete_organization_name
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
        post 'reset_password'
      end
    end

    devise_for :users
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :name, presence: true
  validates :surname, presence: true
  validates :patronymic, presence: true
  validates :phone_number, presence: true
  validates :department_id, presence: true
  belongs_to :department
  has_many :calendar_lists

  default_scope { order('boss DESC, surname ASC') }



  def fio
    self.surname + ' ' + self.name + ' ' + self.patronymic
  end

  def self.search params
    Employee.where('lower(surname) LIKE lower (?) or lower(phone_number) Like lower(?)', "%#{params[:search]}%", "%#{params[:search]}%")
  end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::ApplicationController

  load_resource param_method: :params_employee
  load_resource :class=> Employee 
  authorize_resource

  after_action :get_employees, only: [:create, :update]
  
  def index
    @cabinets = Department.order(:id)
    @phones = Employee.order('boss DESC, surname ASC')

    @em =Department.joins(:employees)
  end

  def new
    @phone = Employee.new
  end

  def edit
    @phone = Employee.find(params[:id])
    if params[:employee].present?
      respond_to do |format|
        if @phone.update_attributes(params_employee)
          format.html { redirect_to(:back, notice: 'Обновлено') }
          format.json { respond_with_bip(@phone) }
        else
          format.html { render action: "edit" }
          format.json { respond_with_bip(@phone) }
        end
      end
    end
  end

  def create
    @phone = Employee.create(params_employee)
    if @phone.save
      redirect_to :back, notice: "Вы добавили сотрудника #{@phone.surname}"
    else
      redirect_to :back, notice: 'Сотрудник не может быть добавлен, возможно не заполнены поля'
    end
  end

  def update
    @phone = Employee.find(params[:id])
    if @phone.update_attributes(params_employee)

      redirect_to :back, notice: "Обновлены данные для сотрудника #{@phone.surname}"
    else
      redirect_to :back, notice: 'Данные не могут быть обновлены'
    end
  end

  def destroy
    @phone = Employee.find(params[:id])
    @phone.destroy
    redirect_to :back
  end



private

  def params_employee
    params.require(:employee).permit!
  end
end

app/views/admin/employees/_form.haml
= simple_form_for phone, url: url, method: met  do |f|
  .modal-body
    =label :boss, 'Начальник отдела'
    =f.check_box :boss
    %br
      %br

    =label :surname,'Фамилия:'
    =f.text_field :surname, class: 'form-control'
    =label :name,'Имя:'
    =f.text_field :name, class: 'form-control'
    =label :patronymic,'Отчество:'
    = f.text_field :patronymic, :class => "form-control"
    =label :phone_number,'Телефон'
    = f.text_field :phone_number, :class => "form-control"
    =label :department_id,'Отдел:'
    = f.select :department_id, options_from_collection_for_select(Department.all, :id, :name, { :selected => @phone.department_id.present? ? @phone.department_id : nil}),{include_blank: 'Выберите отдел'}, { class: 'form-control'}

  .modal-footer
    = f.submit slovo, class: 'btn btn-primary btn-lg btn-block'
  %p
    = link_to admin_department_index_path, class: 'btn btn-success ' do
      < Назад к отделам
  %p
    = link_to admin_employees_path, class: 'btn btn-success ' do
      < Назад к сотрудникам
  %p
    = link_to "1 шаг назад", "javascript:history.go(-1);"

app/views/admin/employees/_table_employee.haml
%table.table.table-bordered.table-condensed.table-hover
  - department.employees.each do |employee|
    %tr
      %td{style: "width: 35%;"}
        = link_to edit_admin_employee_path(employee), title: 'Редактирование' do
          %i.fa.fa-pencil
        =link_to admin_employee_path(employee), title: 'Удаление', method: :delete, data: {confirm: 'Удалить?'} do
          %i.fa.fa-trash-o
        #{employee.fio}
      %td{style: "width: 15%;"}
        =employee.phone_number
        %p

app/views/admin/employees/edit.haml
.container-fluid
  .row
    .col-md-2
    .col-md-8
      .row
        .panel.panel-info
          .panel-heading
            Панель администратора > О нас > Телефонный справочник > Редактирование

          .panel-body
            .text-info{style:"font-size: 15px;"}
            = render 'form', phone: @phone, url: admin_employee_path(@phone), met: 'put', slovo:"Изменить"
            -#, opt: { :selected => @phone.department_id}

app/views/admin/employees/index.haml
- title 'Телефоны МИАЦ Калужской области'
- meta_tag :description, 'сотрудники и их контактные телефоны медицинского информационно-аналитического центра Калужской области'
- meta_tag :keywords, 'сотрудники МИАЦ Калуга, телефон, как связатьсяб телефонная книга, МИАЦ Калуга'
.container-fluid
  .row
    .col-md-2
    .col-md-8
      %p
        = link_to new_admin_employee_path, class: 'btn btn-danger' do
          Добавить сотрудника

        -#= link_to 'Сформировать Excel с телефонами', get_employees_admin_employees_path, class: "btn btn-primary"
      .panel.panel-info{style:"font-size: 14px;"}
        .panel-heading
          .row
            .col-md-10
              %i
                .path
                  Панель администратора > О нас > Телефонный справочник
            .col-md-2
        .panel-body

          %p
          - @cabinets.each do |department|
            -#%tr
            -#  %td{style:"colspan: 2;"}
            %strong
              %i #{department.name} (кабинет № #{department.cabinet_number})

            -#%tr
            =render 'table_employee', department: department

        %br
        %br

app/views/admin/employees/new.haml
.container-fluid
  .row
    .col-md-2
    .col-md-8
      .row
        .panel.panel-info
          .panel-heading
            Панель администратора > О нас > Телефонный справочник > Создание

          .panel-body
            .text-info{style:"font-size: 15px;"}
            = render 'form', phone: Employee.new, url: admin_employees_path, met: 'post', slovo:"Создать"