config/routes.rb
Rails.application.routes.draw do

  get 'politika', :to => redirect('/Politika.pdf')
  get 'calendar_2018', :to => redirect('/calendar_2018.pdf')
  get 'calendar_2019', :to => redirect('/calendar_2019.pdf')

  resources :feedback do
    collection do
      post 'create'
      get :autocomplete_organization_name

    end
  end
  get 'sitemap' => 'main#sitemap'

  mount RedactorRails::Engine => '/redactor_rails'

  root 'main#index'
  get 'about' => "main#about"
  resources :main do
    collection do
      post 'global_search'
      post 'articles'
    end
  end

  resources :rmi
  resources :calendar, only: :index do
        member do
          get 'download_document'
        end
  end

  resources :classroom do
    collection do
      get 'show_video_list'
    end
  end

  resources :organization, :only =>  [:index]  do
    collection do
      get 'info'
      post 'info'
      get 'summary_nok'
      get 'equipment'
    end
  end

  resources :articles, :only =>  [:index, :show]  
  get 'rss' => 'articles#feed', format: 'rss'

  resources :subscribes
  get 'confirm_email' => 'subscribes#confirm'
  get 'unsubscribe' => 'subscribes#unsubscribe'
  post 'send_unsubscribe' => 'subscribes#send_unsubscribe'

    

  resources :statistics, :only =>  [:index]  do
    collection do
      get 'chart'
      get 'docs'
      get 'additionally'
    end

  end

  resources :ratings, only: [:index, :edit] do
    collection do
      get 'add_ambul'
      get 'add_hospital'
      get 'list'
      get 'add_question'
      get 'add_form'
      get 'thank_you'
      get 'edit_form'
      get 'edit_question'
      get 'edit_answer'
      post 'add_ambul'
      post 'add_hospital'
      post 'list'
      post 'add_question'
      post 'add_form'
      put 'edit_form'
      put 'edit_question'
      put 'edit_answer'
    end
  end

  resources :documents

  resources :about do
    collection do
      get 'tasks'
      get 'contacts'
      get 'departments'
      get 'phones'
      get 'vacancies'

    end
  end

  devise_for :users

  resources :eco, only: :index do
    collection do
      post 'create_eco_vote'

    end
  end

  resources :users do
    collection do
      get :autocomplete_organization_name
    end
  end

  namespace :admin do
    namespace :calendar do
      resources :calendar_list do
        member do
          get 'file_list'
          get 'download_document'
          delete 'remove_file'
        end
        collection do
          post 'upload_document'

        end
      end
      resources :calendar_report_type
      resources :calendar_schedule do
        collection do 
          get 'delete_list'
          post 'delete_list'
        end
        
      end
      
    end

    resources :main, only: :index
    resources :articles

    resources :documents do
      collection do
        post 'mass_deleting'
      end
    end
    
    resources :document_stages 

    resources :classroom, :only => [:index, :new, :show_video_list, :destroy, :show, :edit] do
      collection do
        post 'update_video_list'
        get 'update_video_list'
        get 'show_video_list'
        post 'create_video_file'

      end
      member do
        post 'edit'
      end

    end

    resources :organization

    resources :type_organization

    resources :rmi do
      collection do
        get 'theme'
        get 'answer'
        post 'create_answer'
      end

      member do

        get 'edit_theme'
        post 'edit_theme'
        delete 'destroy_theme'
        get 'edit_answer'
        post 'update_answer'

        delete 'destroy_answer'

      end

    end
    resources :vacancies do
      collection do
        post 'create_vacancy'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end

    resources :employees do
      collection do
        get 'get_employees'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end
    resources :department

    resources :users do
      collection do
        get :autocomplete_organization_name
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
        post 'reset_password'
      end
    end

    devise_for :users
  end

end

app/views/shared/_document.haml
.container-fluid
  %br
  .row
    .col-md-12
      .pull-right
        - if request.path ==  admin_documents_path
          = link_to "Добавить документ в этот раздел", "#", "data-target" => "#documentModal", "data-toggle" => "modal", class: "btn btn-success"
          = link_to "Массовое удаление документов", "#", "data-target" => "#documentDeletedModal", "data-toggle" => "modal", class: "btn btn-danger"
  %br
  -if @left_menu.present?
    .row
      .col-md-3
        %ul.nav.nav-pills.nav-stacked.my-left-menu
          - @left_menu.each do |document_stage|
            %li{class: (@document_stage_id.to_i == document_stage.id ? "active_doc" : " ")}
              - if request.path == admin_documents_path
                %a{href: admin_documents_path(document_stage_id: document_stage, parent_id: params[:parent_id])} #{document_stage.name}

              - if request.path == documents_path
                %a{:href => documents_path(document_stage_id: document_stage, parent_id: params[:parent_id])} #{document_stage.name}


        - if params[:document_stage_id].present?
          - current_doc_stage = DocumentStage.find(params[:document_stage_id]).name
        - else
          - current_doc_stage = DocumentStage.where(parent_id: params[:parent_id]).present? ? DocumentStage.where(parent_id: params[:parent_id]).order(:name).first.name : []
      .col-md-9
        =render 'shared/document_body'
  -else
    .col-md-12
      =render 'shared/document_body'

app/views/shared/_document_body.haml
- if params[:document_stage_id].present?
  - current_doc_stage = DocumentStage.find(params[:document_stage_id]).name
- else
  - current_doc_stage = DocumentStage.where(parent_id: params[:parent_id]).present? ? DocumentStage.where(parent_id: params[:parent_id]).order(:name).first.name : []

- if params[:search].present?
  %center
    %u Результаты поиска
.row
  .col-md-6
    %i
      .path
        -if current_doc_stage.present?
          Документы > #{DocumentStage.find(params[:parent_id]).name} > #{current_doc_stage}
        -else
          Документы > #{DocumentStage.find(params[:parent_id]).name}
  .col-md-6
    .pull-right
      %form.form-inline
        .form-group
          .input-group-sm{style:'font-size:13.5px;'}
            

            = link_to 'Показать все', documents_path(document_tab_stage_id:  params[:document_tab_stage_id], document_stage_id: params[:document_stage_id], parent_id: params[:parent_id],  view: 'all', search: params[:search]), class: (params[:view]=='all'  ? 'active_link' : '')
            |
            = link_to 'Показать по 12', documents_path(document_tab_stage_id:  params[:document_tab_stage_id],document_stage_id: params[:document_stage_id], parent_id: params[:parent_id], per_page: 12, search: params[:search]), class: ((params[:per_page]=='12' || params[:view].blank? && params[:per_page].blank?) ? 'active_link' : '')
            |
            = link_to 'Показать по 24', documents_path(document_tab_stage_id:  params[:document_tab_stage_id],document_stage_id: params[:document_stage_id], parent_id: params[:parent_id], per_page: 24, search: params[:search]), class: (params[:per_page]=='24' ? 'active_link' : '')


            = form_tag(request.path, method: "post", class: "form-horizontal") do
              = text_field_tag :search, params[:search], placeholder: "Поиск по разделу", class: "form-control"
              = submit_tag 'Найти', class: 'btn btn-sm btn-primary'
              = hidden_field_tag :parent_id, params[:parent_id]
              = hidden_field_tag :document_stage_id, params[:document_stage_id]
              = hidden_field_tag :document_tab_stage_id, params[:document_tab_stage_id]


.row
  .col-md-12
    %ul.nav.nav-tabs
      -@tab_menu.each do |tab|
        %li{class: (tab.id.to_i == @document_tab_stage_id.to_i ? 'active' : '')}
          - if request.path == documents_path
            %a{:href => documents_path(document_tab_stage_id: tab.id, parent_id: params[:parent_id], document_stage_id: params[:document_stage_id])} #{tab.name}
          - if request.path == admin_documents_path

            %a{:href => admin_documents_path(document_tab_stage_id: tab.id, parent_id: params[:parent_id], document_stage_id: params[:document_stage_id])} #{tab.name}

.row
  .col-md-12
    - if @documents.present?
      %table.table.table-hover.table-condensed
        - @documents.each do |doc|
          %tr
            %td
              .row
                .col-md-2{style:'font-size:13.5px;'}
                  .pull-left
                    %i.fa-fw.fa.fa-calendar
                    = I18n. l doc.created_at, format: '%d/%m/%Y'

                .col-md-1
                  .pull-left
                    - if request.path == documents_path
                      -image = doc.filename.match('doc|docx|pdf|tif|xls|ppt|pptp|rtf|zip|jpg')
                      - if image.present?
                        -image_png = image.to_s + '.png'
                        %a.tooltips{"data-original-title" => "#{doc.filename}", "data-placement" => "top", "data-toggle" => "tooltip", :href => document_path(doc), :title => "Скачать документ"}

                          = image_tag(image_png, style: "width: 40px;")
                      - else
                        %a.tooltips{"data-original-title" => "#{doc.filename}", "data-placement" => "top", "data-toggle" => "tooltip", :href => document_path(doc), :title => "Скачать документ"}
                          = image_tag('file.png', style: "width: 40px;")
                    - elsif request.path ==  admin_documents_path
                      -if current_user.admin || (can? :manage, Document)
                        = link_to admin_document_path(doc), method: :delete, data: {confirm: 'Вы уверены, что хотите удалить документ?'}, class: 'btn btn-sm btn-danger' do
                          %i.fa.fa.fa-trash-o

                .col-md-6
                  %h4
                    %strong
                      %i
                        = link_to doc.filename, document_path(doc), title: 'Скачать документ'
                .col-md-3
                  .pull-right
                    %form.form-inline
                      .form-group
                        .input-group-sm
                          %a.tooltips{"data-original-title" => "#{doc.filename}", "data-placement" => "top", "data-toggle" => "tooltip", :href => document_path(doc), :title => "Скачать документ"}
                            = image_tag('download_doc.png', style: "width: 40px;")
                          %i.fa.fa.fa-signal{title: 'Просмотров'}
                          .badge
                            =doc.count_download

      %center
        = will_paginate @documents, :previous_label => t("<"), :next_label => t(">")
      %br
        %br

    - elsif params[:search].present?
      .text-info.text-center
        %h3
          По вашему запросу в данном разделе не найдено ни одного документа
    - elsif @documents.blank? && params[:search].blank?
      %br
        %br
      .text-info.text-center
        %h3
          В раздел не загружен ни один документ

app/views/shared/_modal_bars.haml
#barsModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "margin-top: 200px; width:80%; z-index: 99999;"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#mednetModalLabel.modal-title Переход в ИАС БАРС
      .modal-body
        %center
          %p
            %h3{style: "color: red;"}
              Обращаем Ваше внимание, что доступ к системе БАРС ОГРАНИЧЕН!!!
        %p
          %strong
            В случае возникновении проблемы при загрузке страницы после нажатия на кнопку "Перейти в ИАС БАРС", необходимо обратится за консультациями по телефону 8 (4842) 70-50-04 доб 46.
        %p{style: "font-size: 9px;"}
          %i
            *Для дальнейшей работы с закрытой системой будет взят Ваш ip адрес: #{request.remote_ip}
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Закрыть
        = link_to 'Перейти в ИАС БАРС', 'http://10.2.1.127:88/SVODY/', class: 'btn btn-primary','data-loading-text'=> "Осуществляется переход..."

app/views/shared/_org_top.haml
%ul.dropdown-menu
  %li
    .mega-menu-content.disable-icons
      .container
        .row.equal-height
          .col-md-12.equal-height-in
            %ul.list-unstyled.equal-height-list
              - TypeOrganization.order(id: :asc).in_groups_of(4, false).each do |two_w|
                .col-md-4
                  - two_w.each do |w|
                    %li
                      %h4
                        = w.name
                    - Organization.where(type_org_id: w.id).each do |r|
                      %li
                        = link_to "#{r.name}", info_organization_path(r.id)

app/views/shared/_sidebar.haml
- if request.path == classroom_index_path || request.path == show_video_list_classroom_index_path

  - if params[:act] == 'video'
    - if user_signed_in? and current_user.admin?
      = link_to "Обновить список", update_video_list_classroom_index_path
    - if @channel.present?
      %ul.nav.navbar-nav
        %li
          %a.tooltips{"data-original-title" => "Youtube", "data-placement" => "top", "data-toggle" => "tooltip", :href => "https://www.youtube.com/channel/UCGZD4qjOnUS6NP9i5KNQ0hA", :title => "Ссылка на наш канал в Youtube", :target => :blank}
            -#%i.fa.fa-youtube
            = image_tag('youtube.png', style: "width: 120px;")

        - @channel.each do |rec|
          %li{class: ( params[:id].to_i==rec.id.to_i ?  "acti" : "")}
            = link_to rec.title, show_video_list_classroom_index_path(id: rec.id, act: 'video')
          %br

- if request.path == documents_path
  - if DocumentStage.all.present?
    %ul.nav.navbar-nav
      %li
        = image_tag('documents.png', style: "width: 60px;")

        - DocumentStage.where("parent_id is null").order(:name).each do |doc_stage|
          %li
            %strong
              = doc_stage.name
          - DocumentStage.where(parent_id: doc_stage.id).each do |doc_parent|
            %li.paren{class: ( params[:document_id].to_i==doc_parent.id.to_i ?  "acti" : "")}
              = link_to doc_parent.name, documents_path(document_id: doc_parent.id)




  - else
    Не добавлено ни одного раздела

app/views/shared/_social_share.haml
%script{:src => "//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"}
%script{:src => "//yastatic.net/share2/share.js"}
.ya-share2{"data-services" => "vkontakte,facebook,odnoklassniki, gplus", "data-size" => "s"}

app/views/shared/_topbar.haml
.container
  .topbar
    %ul.loginbar.pull-right
      %li
        - unless user_signed_in?
          = link_to "#", "data-target" => "#myModal", "data-toggle" => "modal" do
            %i.fa.fa-sign-in
            Вход

        - else
          = link_to "#{current_user.email}",destroy_user_session_path, :method => :delete, :data => { :confirm => 'Вы уверены, что хотите выйти из системы?' }
      |

      %li
        = link_to "#", "data-target" => "#mednetModal", "data-toggle" => "modal" do
          %i.fa.fa-user-secret
          Вход в mednet


    %br
    
.nav.navbar{style: "margin-bottom: 9px;"}
  %a.navbar-brand{:href => "#"}
    = image_tag('MIAC_full_grey.png', style: "width: 160px; margin-top: -3%;")
  .container-fluid
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.fa.fa-bars
    .navbar-header
    .collapse.navbar-collapse.mega-menu.navbar-responsive-collapse
      .container.top_links
        %ul.nav.navbar-nav
          %li{class: (request.path == root_path ? "active" : " ")}
            = link_to root_path do
              %i.fa.fa-home.fa-lg
          %li{class: (request.path == articles_path ? "active" : " ")}
            = link_to "Новости",  articles_path
          -#%li
          -#  = link_to "Материалы", root_path
          %li.dropdown{class: request.path == statistics_path ? "active": "" }
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);"}
              Статистика
            %ul.dropdown-menu
              %li
                = link_to "Статистика", statistics_path

              %li
                = link_to "Графики", chart_statistics_path
              %li
                = link_to "Информация и документы", docs_statistics_path
              %li
                = link_to "Выездные проверки", additionally_statistics_path
            %li{class: (request.path == documents_path ? "active" : " ")}
              - if Document.all.count > 0

                - param = documents_path(document_id: Document.first.document_stage_id)
              - else
                - param =documents_path

              = link_to "Документы", param




          - if TypeOrganization.present?
            %li.dropdown.mega-menu-fullwidth
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);"}
                Учреждения
              = render 'shared/org_top'

          %li{class: request.path == projects_path ? "active": "" }
            = link_to "Информатизация", projects_path
          %li{class: (request.path == show_video_list_classroom_index_path || request.path == classroom_index_path) ? "active": "" }
            - if VideoPlaylist.all.count > 0

              - param = show_video_list_classroom_index_path(act: 'video', id: VideoPlaylist.first.id  )
            - else
              - param = classroom_path
            = link_to "Видеоматериалы", param
          -#%li.dropdown{class: request.path == show_video_list_classroom_index_path ? "active": "" }
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);"}
              Обучение
            %ul.dropdown-menu
              %li
                = link_to 'Методические пособия', classroom_index_path(act: 'book')
              %li
                = link_to 'Видеоматериалы', show_video_list_classroom_index_path(act: 'video', id: VideoPlaylist.first.id  )
          -#%li{class: request.path == classroom_index_path ? "active": "" }
          -#  = link_to "Курсы/Обучение", classroom_index_path
          -#%li{class: request.path == service_pat h ? "active": "" }
          -#  = link_to "Услуги", service_path
          %li{class: request.path == about_path ? "active": "" }
            = link_to "О нас", about_path

          %li{class: request.path == calendar_path ? "active": "" }
            = link_to "Календарь отчетности", calendar_path

app/views/shared/_topbar_welcome_admin.haml
- if current_user.present? && (current_user.admin == true || current_user.moderator == true || current_user.boolean == true)
  .container-fluid.top_logo
    .row
      .col-md-8
        .top_welcome
          .container-fluid
            %center
              Панель администратора официального сайта Медицинского информационно-аналитического центра Калужской области.

      .col-md-4
        .pull-right
          - unless user_signed_in?
            = link_to "#", "data-target" => "#myModal", "data-toggle" => "modal" do
              %i.fa.fa-sign-in
              Вход
          - else
            Вы зашли как
            = current_user.username
            = link_to "Выход",destroy_user_session_path, :method => :delete, :data => { :confirm => 'Вы уверены, что хотите выйти из системы?' }




  %nav.navbar.navbar-admin{"data-offset-top" => "110", "data-spy" => "affix;"}
    .container-fluid
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.fa.fa-bars
      .navbar-header
      .collapse.navbar-collapse.mega-menu.navbar-responsive-collapse
        .container.top_links
          %ul.nav.navbar-nav
            %li
              %a{:href => root_path}
                %i.fa.fa.fa-arrow-left
                На сайт
            %li{class: (request.path == admin_main_index_path  ? "active_doc" : " ")}
              %a{:href => admin_main_index_path}
                %i.fa.fa.fa-bar-chart-o
                Сводка
            -if can? :manage, Article
              %li{class: (request.path == admin_articles_path  ? "active_doc" : " ")}
                %a{:href => admin_articles_path}
                  %i.fa.fa.fa-list
                  Новости

            -if can? :manage, Document
              - if DocumentStage.all.present?
                %li.dropdown.mega-menu-fullwidth
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: params[:parent_id].present? ? "active_doc" : " "}
                    %i.fa.fa.fa-file
                    Документы
                  %ul.dropdown-menu
                    - DocumentStage.where("parent_id is null").order(:name).each do |doc_stage|
                      %li{class: (params[:parent_id].present? ? "active_drop" : " ")}
                        %a{href: admin_documents_path(parent_id: doc_stage)} #{doc_stage.name}

                    %li.divider{role: 'separator'}
                    %li
                      %a{href: admin_document_stages_path} Разделы документов

              -if can? :manage, VideoPlaylist
                %li{class: request.path == show_video_list_admin_classroom_index_path ? "active_doc": "" }
                  - if VideoPlaylist.all.count > 0

                    - param_video = show_video_list_admin_classroom_index_path(id: VideoPlaylist.first.id  )
                  - else
                    - param_video = admin_classroom_path
                  %a{:href => param_video}
                    %i.fa.fa.fa-video-camera
                    Видеоматериалы




              -if can? :manage, Organization
                %li.dropdown.mega-menu-fullwidth
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: (params[:type_organization].present? || request.path == summary_nok_organization_index_path ? "active_doc" : " ")}
                    %i.fa.fa.fa-home
                    Учреждения здравоохранения
                  %ul.dropdown-menu
                    - TypeOrganization.joins(:organizations).order('type_organizations.name').select('type_organizations.id, type_organizations.name').distinct.each do |type|
                      %li{class: request.path ==  admin_organization_index_path ? "active_doс" : " "}
                        %a{:href => admin_organization_index_path(type_organization_id: type.id)} #{type.name}
                    %li.divider{role: 'separator'}
                    %li
                      %a{href: admin_type_organization_index_path} Типы организаций
              -if can? :manage, FaqRmisTheme
                %li.dropdown.mega-menu-fullwidth
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: (params[:type_organization].present? ? "active_doc" : " ")}
                    %i.fa.fa.fa-medkit
                    РМИС
                  %ul.dropdown-menu
                    %li
                      %a{:href => theme_admin_rmi_index_path} Темы для вопросов
                    %li
                      %a{:href => answer_admin_rmi_index_path} Ответы на вопросы
              -if (can? :manage, Employee) || (can? :manage, Vacancy)
                %li.dropdown.mega-menu-fullwidth
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: (params[:type_organization].present? ? "active_doc" : " ")}
                    %i.fa.fa.fa-sitemap
                    О нас
                  %ul.dropdown-menu
                    %li
                      %a{:href => admin_vacancies_path} Вакансии
                    %li
                      %a{:href => admin_employees_path} Телефонный справочник
                    %li
                      %a{:href => admin_department_index_path} Отделы
              -if current_user.present? && current_user.admin
                %li{class: request.path == admin_users_path ? "active_doс" : " "}
                  = link_to admin_users_path do
                    %i.fa.fa-users
                    Пользователи

              -if can? :manage, User
                %li{class: request.path == admin_users_path ? "active_doс" : " "}
                  = link_to edit_user_registration_path do
                    %i.fa.fa-pencil
                    Мой профиль

              -if can? :manage, CalendarList
                %li.dropdown.mega-menu-fullwidth
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: (params[:controller].match('calendar').present? && params[:controller].match('admin').present? ? "active_doc" : " ")}
                    %i.fa.fa.fa-sitemap
                    календарь отчетности
                  %ul.dropdown-menu
                    %li
                      %a{:href => admin_calendar_calendar_list_index_path} Отчеты МИАЦ
                    %li
                      %a{:href => admin_calendar_calendar_report_type_index_path} Типы отчетов
                    %li
                      %a{:href => admin_calendar_calendar_schedule_index_path} Расписания
                    %li{class: request.path==calendar_2018_path ? 'active':''}
                      %a{href: calendar_2018_path, target: :blank} Производственный календарь 2018
                    %li{class: request.path==calendar_2019_path ? 'active':''}
                      %a{href: calendar_2019_path, target: :blank} Производственный календарь 2019

              -#%li{class: request.path == video_playlist_admin_documents_path ? "active_drop" : " "}
                %a{href: video_playlist_admin_documents_path} Разделы видео


              -#%li.dropdown.mega-menu-fullwidth
              -#  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: ((params[:parent_id].present? && params[:parent_id].to_i == DocumentStage.medstat[:parent_id]) ? "active_doc" : " ")}
              -#    Медицинская статистика
              -#  %ul.dropdown-menu
              -#    - DocumentStage.medstat[:document_stage_id].each do |doc_stage|
              -#      %li{class: (DocumentStage.medstat[:document_stage_id].pluck(:id).include? params[:document_stage_id] ? "active_drop" : " ")}
              -#        %a{href: documents_path(document_stage_id: doc_stage, parent_id: DocumentStage.medstat[:parent_id])} #{doc_stage.name}
            -#- else
            -#  %li{class: (request.path == documents_path  ? "active_doc" : " ")}
            -#    %a{:href => documents_path} Документы
            -#
            -#%li{class: (request.path == show_video_list_classroom_index_path || request.path == classroom_index_path) ? "active_doc": "" }
            -#  - if VideoPlaylist.all.count > 0
            -#
            -#    - param_video = show_video_list_classroom_index_path(id: VideoPlaylist.first.id  )
            -#  - else
            -#    - param_video = classroom_path
            -#  %a{:href => param_video} Видеоматериалы
            -#- if TypeOrganization.present?
            -#  %li.dropdown.mega-menu-fullwidth
            -#    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: (params[:type_organization].present? ? "active_doc" : " ")}
            -#      Учреждения здравоохранения
            -#    %ul.dropdown-menu
            -#      - TypeOrganization.order(:id).each do |type|
            -#        %li
            -#          %a{:href => info_organizations_path(type_organization: type)} #{type.name}
            -#%li{class: (request.path == about_path ? "active_doc" : " ")}
            -#  %li.dropdown.mega-menu-fullwidth
            -#    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "javascript:void(0);", class: ((request.path == contacts_about_index_path || request.path == phones_about_index_path || request.path == departments_about_index_path || request.path ==tasks_about_index_path) ? "active_doc" : " ")}
            -#      О нас
            -#    %ul.dropdown-menu
            -#      %li
            -#        %a{:href => tasks_about_index_path} Задачи МИАЦ
            -#      %li
            -#        %a{:href => contacts_about_index_path} Контактная информация
            -#      %li
            -#        %a{:href => departments_about_index_path} Отделы МИАЦ
            -#      %li
            -#        %a{:href => phones_about_index_path} Телефонный справочник