config/routes.rb
Rails.application.routes.draw do

  get 'politika', :to => redirect('/Politika.pdf')
  get 'calendar_2018', :to => redirect('/calendar_2018.pdf')
  get 'calendar_2019', :to => redirect('/calendar_2019.pdf')

  resources :feedback do
    collection do
      post 'create'
      get :autocomplete_organization_name

    end
  end
  get 'sitemap' => 'main#sitemap'

  mount RedactorRails::Engine => '/redactor_rails'

  root 'main#index'
  get 'about' => "main#about"
  resources :main do
    collection do
      post 'global_search'
      post 'articles'
    end
  end

  resources :rmi
  resources :calendar, only: :index do
        member do
          get 'download_document'
        end
  end

  resources :classroom do
    collection do
      get 'show_video_list'
    end
  end

  resources :organization, :only =>  [:index]  do
    collection do
      get 'info'
      post 'info'
      get 'summary_nok'
      get 'equipment'
    end
  end

  resources :articles, :only =>  [:index, :show]  
  get 'rss' => 'articles#feed', format: 'rss'

  resources :subscribes
  get 'confirm_email' => 'subscribes#confirm'
  get 'unsubscribe' => 'subscribes#unsubscribe'
  post 'send_unsubscribe' => 'subscribes#send_unsubscribe'

    

  resources :statistics, :only =>  [:index]  do
    collection do
      get 'chart'
      get 'docs'
      get 'additionally'
    end

  end

  resources :ratings, only: [:index, :edit] do
    collection do
      get 'add_ambul'
      get 'add_hospital'
      get 'list'
      get 'add_question'
      get 'add_form'
      get 'thank_you'
      get 'edit_form'
      get 'edit_question'
      get 'edit_answer'
      post 'add_ambul'
      post 'add_hospital'
      post 'list'
      post 'add_question'
      post 'add_form'
      put 'edit_form'
      put 'edit_question'
      put 'edit_answer'
    end
  end

  resources :documents

  resources :about do
    collection do
      get 'tasks'
      get 'contacts'
      get 'departments'
      get 'phones'
      get 'vacancies'

    end
  end

  devise_for :users

  resources :eco, only: :index do
    collection do
      post 'create_eco_vote'

    end
  end

  resources :users do
    collection do
      get :autocomplete_organization_name
    end
  end

  namespace :admin do
    namespace :calendar do
      resources :calendar_list do
        member do
          get 'file_list'
          get 'download_document'
          delete 'remove_file'
        end
        collection do
          post 'upload_document'

        end
      end
      resources :calendar_report_type
      resources :calendar_schedule do
        collection do 
          get 'delete_list'
          post 'delete_list'
        end
        
      end
      
    end

    resources :main, only: :index
    resources :articles

    resources :documents do
      collection do
        post 'mass_deleting'
      end
    end
    
    resources :document_stages 

    resources :classroom, :only => [:index, :new, :show_video_list, :destroy, :show, :edit] do
      collection do
        post 'update_video_list'
        get 'update_video_list'
        get 'show_video_list'
        post 'create_video_file'

      end
      member do
        post 'edit'
      end

    end

    resources :organization

    resources :type_organization

    resources :rmi do
      collection do
        get 'theme'
        get 'answer'
        post 'create_answer'
      end

      member do

        get 'edit_theme'
        post 'edit_theme'
        delete 'destroy_theme'
        get 'edit_answer'
        post 'update_answer'

        delete 'destroy_answer'

      end

    end
    resources :vacancies do
      collection do
        post 'create_vacancy'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end

    resources :employees do
      collection do
        get 'get_employees'
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
      end
    end
    resources :department

    resources :users do
      collection do
        get :autocomplete_organization_name
      end
      member do
        put 'edit'
        get 'edit'
        post 'edit'
        post 'reset_password'
      end
    end

    devise_for :users
  end

end

app/models/department.rb
class Department < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true


  has_many :employees, :dependent => :restrict_with_error

  default_scope { order('id ') }
  

  def self.search params
    Department.where('name LIKE lower (?) ', "%#{params[:search]}%")
  end

  def self.initial
    Department.create(name: 'Директор', cabinet_number: '1')
    Employee.create(name: 'xxx', surname: 'xxx', patronymic: 'xxxx', phone_number:'xxx (доб.11)', department_id: Department.last.id )

    Department.create(name: 'Административный отдел', cabinet_number: '10 и 11')
    Employee.create(name: 'xxx', surname: 'xxx', patronymic: 'xxx', phone_number:'xxx', department_id:  Department.last.id )
    Employee.create(name: 'xxx', surname: 'xxx', patronymic: 'xxx', phone_number:'xxx', department_id:  Department.last.id )


  end
end

app/controllers/admin/department_controller.rb
class Admin::DepartmentController < Admin::ApplicationController

  load_resource param_method: :params_depart
  load_resource :class=> Department
  authorize_resource
  after_action :get_employees, only: [:create, :update]
  before_action :departments

  def index
    @departments = Department.order(:id)
  end

  def edit
    @department = Department.find(params[:id])
  end

  def create
    @department = Department.create(params_depart)
    if @department.save
      redirect_to admin_department_index_path, notice: "#{@department.name} создан"
    else
      redirect_to admin_department_index_path, notice: 'Отдел не может быть создан, не хватает информации'
    end
  end


  def update
    @department = Department.find(params[:id])
    if params[:department].present?
      respond_to do |format|
        if @department.update_attributes(params_depart)
          format.html { redirect_to(admin_department_index_path, notice: 'Обновлено') }
          format.json { respond_with_bip(@department) }
        else
          format.html { render action: "edit" }
          format.json { respond_with_bip(@department) }
        end
      end
    end
    # if @department.update_attributes(params_depart)
    #   redirect_to admin_department_index_path, notice: "Обновлена информация для #{@department.name}"
    # else
    #   render "edit"
    # end
  end



  def destroy
    department = Department.find(params[:id])
    respond_to do |f|
      if department.destroy.present?
        f.js { render layout: false, content_type: 'text/javascript' }
      else
        f.js {render js: "alert('Ошибка при удалении. За данным отделом закреплены сотрудники')"}
      end
    end
  end

  def departments
    @departments = Department.order(id: :asc)
  end

private

  def params_depart
    params.require(:department).permit!
  end

end

app/views/admin/department/_departments.haml
- @departments.each do |department|
  .panel.panel-info
    .panel-heading
      = best_in_place department, :name, :as => :textarea, url: admin_department_path(department.id)
      %span (кабинет №
      = best_in_place department, :cabinet_number, :as => :input, url: admin_department_path(department.id)
      %span )
      = link_to edit_admin_department_path(department), title: 'Редактировать отдел' do
        %i.fa.fa-pencil

      = link_to admin_department_path(department), method: :delete, remote: true, title: 'Удаление', data: { confirm: 'Вы уверены, что хотите удалить?' } do
        %i.fa.fa-trash-o{style: "color:red"}
    .panel-body{style:"font-size: 16px;"}

      %span
        %strong.text-info
          = best_in_place department, :description, :as => :textarea, url: admin_department_path(department.id)

      =render 'admin/employees/table_employee', department: department

app/views/admin/department/_form.haml
= simple_form_for department, url: url, method: met  do |f|
  %br
    =label :name,'Наименование отдела:'
    =f.text_field :name, class: 'form-control'
    =label :cabinet_number,'Номер кабинета отдела:'
    =f.text_field :cabinet_number, class: 'form-control'
    =label :description,'Описание отдела:'
    =f.text_area :description, :class => "redactor", :rows => 40, :cols => 120

    = f.submit slovo, class: 'btn btn-primary btn-lg btn-block'

app/views/admin/department/destroy.js.erb
$('#t').html('<%= j render(partial: 'departments') %>');

app/views/admin/department/edit.haml
.container-fluid
  .row
    .col-md-2
    .col-md-8
      .row
        .panel.panel-info
          .panel-heading
            Панель администратора > О нас > Отделы > Редактирование

          .panel-body
            .text-info{style:"font-size: 15px;"}
            = render 'form', department: @department, url: admin_department_path(@department), met: 'put', slovo:"Изменить"
            = link_to admin_department_index_path, class: 'btn btn-success ' do
              < Назад

app/views/admin/department/index.haml
.container-fluid
  .row
    .col-md-1
    .col-md-10
      .row
        .pull-right
          %br
          %p
            = link_to new_admin_department_path, class:'btn btn-success' do
              Добавить отдел

            = link_to new_admin_employee_path, class: 'btn btn-primary', title: 'Добавить сотрудника' do
              Добавить сотрудника
        %br
          %br
        .well{style: "color:black"}
          %i
            .path
              Панель администратора > О нас > Отделы МИАЦ
          %br
          #t{style: 'padding: 2em;'}=render 'departments'

app/views/admin/department/new.haml
.container-fluid
  .row
    .col-md-2
    .col-md-8
      .row
        .panel.panel-info
          .panel-heading
            Панель администратора > О нас > Отделы > Добавление

          .panel-body
            .text-info{style:"font-size: 15px;"}
            = render 'form', department: Department.new, url: admin_department_index_path, met: 'post', slovo:"Добавить"
            = link_to admin_department_index_path, class: 'btn btn-success ' do
              < Назад